homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret accurate_latitude
  longitude: !secret accurate_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 43
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Jerusalem
  # Customization file
  auth_providers:
      - type: homeassistant
      - type: legacy_api_password
        api_password: !secret http_password
  customize: !include customize.yaml

  packages: !include_dir_named pkgs

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: hhaim
  password: !secret mqtt_password
  protocol: 3.1
  birth_message:
    topic: "tele/hass1/LWT"
    payload: "Online"
    qos: 1
    retain: true
  will_message:
    topic: "tele/hass1/LWT"
    payload: "Offline"
    qos: 1
    retain: true

http:
  # Secrets are defined in the file secrets.yaml
  #api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  #trusted_networks:
  #      - 127.0.0.1
  #      - 10.0.0.0/24

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

#logger:
#  default: critical
#  logs:
#    homeassistant.components.xiaomi_aqara: debug
#    xiaomi_gateway: debug
#
    

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

lovelace:
  mode: yaml

sensor:
  - platform: uptime

duckdns:
  domain: !secret duckdns_domain 
  access_token: !secret duckdns_tocken

# Example configuration.yaml entry
speedtestdotnet:
  scan_interval:
    minutes: 60
  monitored_conditions:
    - ping
    - download
    - upload


# Text to speech
tts:
  - platform: google

# Cloud
cloud:

#  platform: pushbullet
#  api_key: !secret pushbullet

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: notify
    platform: telegram
    api_key: !secret telegram_api_key
    chat_id: !secret telegram_chat_id

  - platform: clicksend
    name: ClickSend
    username: !secret clicksend_user
    api_key: !secret clicksend_api
    recipient: !secret clicksend_phone
    sender: !secret clicksend_sener

  - platform: clicksend_tts
    name: clicksend_tts
    username: !secret clicksend_user
    api_key: !secret clicksend_api
    recipient: !secret clicksend_phone
    caller: !secret clicksend_sener


panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hass.hhaim.home:3218

influxdb:
  database: hass_db

recorder:
  purge_keep_days: 7
  purge_interval: 1
  db_url: !secret recorder_db_url


xiaomi_aqara:
  discovery_retry: 5
  gateways:
      -  mac: !secret mii_mac
         key: !secret mii_key 



system_health:


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
